apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  labels:
    app: sample
spec:
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: sample
        image: hub.regsitry.local:5000/microservice-update:latest
        env:
        - name: HOST
          value: "pgdb.local"
        - name: PORT
          value: "5432"
        - name: PASSWORD
          value: "Strongpwd"
        - name: USERNAME
          value: "postgres"
        - name: MS_PORT
          value: "3043"
        - name: DBNAME
          value: "sample"
        - name: SCHEMANAME
          value: "sample"
        ports:
        - containerPort: 80
        resources: 
          requests:
            cpu: 250m
          limits:
            cpu: 500m
            memory: 250Mi
     