kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v2beta2 
metadata: 
  name: config-registry 
spec: 
  maxReplicas: 10 
  minReplicas: 1 
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: config-registry-deployment 
  metrics: 
  - type: Resource 
    resource: 
      name: cpu 
      target:
        type: Utilization
        averageUtilization: 60