apiVersion: v1
kind: Service
metadata:
  name: config-registry-service
spec:
  type: LoadBalancer
  externalIPs:
  - 172.16.10.54
  selector:
    app: config-registry
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3043
      nodePort: 30043